Added basic implementation for textDocument/definition action
teal-language/teal-language-server pull request #8
Opened 2022-02-21 00:28 UTC by svermeulen

2022-02-21 16:15 UTC, euclidianAce requested changes
Other than the couple of comments I left, looks good! :+1:

2022-02-21 16:15 UTC, euclidianAce commented on src/handlers.tl
> +   local file_uri:uri.ParsedUri
small style typo, should be a space between `file_uri:` and `uri.ParsedUri`

2022-02-21 16:15 UTC, euclidianAce commented on src/path_util.tl
> +
this project depends on [cyan](github.com/teal-language/cyan), which has a decent [path module](https://teal-language.github.io/cyan/index.html#cyan.fs.path) that can do these operations

2022-11-19 15:34 UTC, lewis6991 commented
Is there anything blocking this now?

2022-11-22 18:50 UTC, euclidianAce approved these changes

2022-11-22 18:50 UTC, merged

2022-11-22 18:50 UTC, euclidianAce commented
Sorry for not getting to this quicker! Been real busy as of late. Thanks!